### ISSUE TITLE
Frequency not present in dump of database

### ISSUE THREAD

**Issue by messaoudia** [MLRS/gabra-api#18]
Hi @johnjcamilleri @bertugatt it seems that in the dumps presented [here](https://mlrs.research.um.edu.mt/resources/gabra-api/p/download) you do not have the `frequency` attribute (which is described [here](https://github.com/MLRS/gabra-api/blob/de28d76567fef5967a0abf2e59190180a2c084d3/public/schemas/lexeme.json#L198)) but `norm_freq`.

Is there some threshold that I can use to determine wether a word is common/uncommon/rare ?
![Capture d’écran 2020-10-27 à 17 52 24](https://user-images.githubusercontent.com/4719434/97334553-2d01bf80-187d-11eb-984b-7f9346ed54bf.png)

Thank you !

PS: take care

**Comment by johnjcamilleri** [comment]
Hi Amin,
You're right, the `frequency` field is a relic which is not used. In fact I just removed it from the schema.

As for the thresholds of `norm_freq`, I think you will need to look at the distribution of frequencies and make your own decision on what such thresholds should be. I myself have never worked with that field so I don't have any intuitions about its value.

**Comment by AminMe** [comment]
Ok thanks ! 
I will look into the distribution to make my own decision.

> You're right, the frequency field is a relic which is not used. In fact I just removed it from the schema.
Just for ℹ️ `norm_freq` is not specified in the [doc](https://mlrs.research.um.edu.mt/resources/gabra-api/p/schema) of the api
